bigevent/urls.py
from django.conf.urls import url,include
from auth import views as auth_views
from admin import views as admin_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    url(r'^admin/login/',auth_views.login,name='login'),
    url(r'^admin/register/',auth_views.register,name="register"),
    url(r'^admin/checkUser/',auth_views.checkUser,name="checkUser"),
    url(r'^admin/logout/',auth_views.logout,name="logout" ),
    url(r'^admin/test/',auth_views.test,name="test"),
    url(r'^admin/$', admin_views.index, name="admin-index"),
    url(r'^admin/agencies/', admin_views.agencies, name="admin-agencies"),
    # url(r'^admin/addAgency/',admin_views.addAgency,name="admin-add-agency1"),
    url(r'^admin/addAgency/(\d+)/$',admin_views.addAgency,name="admin-add-agency"),
    url(r'^admin/editAgency/(\d+)/$',admin_views.editAgency,name="admin-edit-agency"),
    url(r'^admin/users/$',admin_views.users, name="admin-users"),
    url(r'^admin/addUser/$',admin_views.addUser,name="admin-add-user"),
    url(r'^admin/test/', admin_views.test, name="admin-test"),
    url(r'^admin/test2/', admin_views.test2, name="admin-test2"),
    url(r'^admin/editUser/(\d+)/$',admin_views.editUser,name="admin-edit-user"),
    url(r'^admin/rules/$',admin_views.rules, name="admin-rules"),
    url(r'^admin/addRule/(\d+)/$',admin_views.addRule,name="admin-add-rule"),
    url(r'^admin/editRule/(\d+)/$',admin_views.editRule,name="admin-edit-rule"),
    url(r'^admin/roles/$',admin_views.roles, name="admin-roles"),
    url(r'^admin/addRole/$',admin_views.addRole,name="admin-add-role"),
    url(r'^admin/editRole/(\d+)/$',admin_views.editRole,name="admin-edit-role"),
    url(r'^admin/setRole/(\d+)/$',admin_views.setRole,name="admin-set-role"),
    url(r'^admin/access/(\d+)/$',admin_views.access,name="admin-access"),
    url(r'^admin/test3/(\d+)/$',admin_views.test3,name="admin-test3"),
    url(r'^admin/testCheck/(.+)/$',admin_views.testCheck,name="admin-test-check"),
    url(r'^bigs/',include('bigs.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bigs/urls.py
from django.conf.urls import url
from bigs import views as bigs_views

urlpatterns = [
    url(r'^$',bigs_views.index,name="bigs-index"),
    url(r'^add/$',bigs_views.add,name="bigs-add"),
    url(r'^(\d+)/edit/$',bigs_views.edit,name="bigs-edit"),
    url(r'^show/(\d+)/$',bigs_views.show,name="bigs-show"),
    url(r'^references/$',bigs_views.references,name="bigs-references"),
    url(r'^addRef/$',bigs_views.addRef,name="bigs-addRef"),
    url(r'^(\d+)/editRef/$',bigs_views.editRef,name="bigs-edit-ref"),
    url(r'^(\d+)/delRef/$',bigs_views.delRef,name="bigs-del-ref"),
    url(r'^(\d+)/showRef/$',bigs_views.showRef,name="bigs-show-ref"),

]

bigs/models.py
from django.db import models
from PIL import Image
from django.utils.encoding import force_text, python_2_unicode_compatible
import uuid
import os

def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('images/', filename)


# Create your models here.
@python_2_unicode_compatible
class Bigs(models.Model):
	user = models.ForeignKey('auth.User')
	topic = models.CharField(u'事件',max_length=160)
	year = models.CharField(u'年代',max_length=50)
	date = models.CharField(u'时间',max_length=50)
	era = models.CharField(u'朝代',max_length=80)
	place = models.CharField(u'地点',max_length=80)
	roles = models.CharField(u'人物',max_length=254)
	content = models.TextField(u'详情')
	refs = models.ForeignKey('Refs')
	memo = models.TextField(u'备注')
	comments = models.TextField(u'点评')
	image = models.ImageField(u'事件图片',upload_to=get_file_path)
	create_time = models.DateTimeField(auto_now_add=True)
	update_time = models.DateTimeField(auto_now=True)
	status = models.SmallIntegerField(default=1)

	def __str__(self):
		return self.topic


@python_2_unicode_compatible
class Refs(models.Model):
    name = models.CharField(u'名称',max_length=100)
    author = models.CharField(u'作者',max_length=100)
    publisher = models.CharField(u'出版社',max_length=100)
    pubtime = models.DateTimeField(u'出版时间')
    isbn = models.BigIntegerField(u'ISBN',max_length=13)
    intro = models.TextField(u'简介')
    cover = models.ImageField(u'封面',upload_to=get_file_path)
    create_time = models.DateTimeField(auto_now_add=True)
    status = models.SmallIntegerField(default=1)

    def __str__(self):
        return self.name

bigs/forms.py
from django import forms
from django.forms import ModelForm
from bigs.models import Bigs,Refs

class BigsForm(ModelForm):

	class Meta:
		model = Bigs
		fields = ['id','topic','year','date','era','place','roles','content','refs','memo','image']

class RefsForm(ModelForm):

	class Meta:
		model = Refs
		fields = ['id','name','author','publisher','pubtime','cover','intro']

bigs/views.py
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import render
from django.template.response import TemplateResponse
from django.db import models
from .models import Bigs,Refs
from auth.models import User
from function.functions import get_tree
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from admin.extpaginator import extpaginator
from django.db.models import Q
from .forms import BigsForm,RefsForm
from django.core.urlresolvers import reverse,resolve

# Create your views here.
def index(request):
	p = request.GET.get('p')
	k = request.GET.get('keyword')
	if p == None:
		p = 1
	if k == None:
		k = ''

	if k != '':
		bigs = Bigs.objects.filter(Q(topic__contains=k)|Q(place__contains=k)|Q(roles__contains=k))
	else:
		bigs = Bigs.objects.all()
	paginator = extpaginator(bigs, 10)
	pagestr = paginator.pagestr(p,{'k':k})
	try:
		pbigs = paginator.page(p)
	except PageNotAnInteger:
		pbigs = paginator.page(1)
	except EmptyPage:
		pusers = paginator.page(paginator.num_pages)
	return TemplateResponse(request, 'bigs/index.html',{'bigs':pbigs, 'pagestr':pagestr})

def add(request):
	if request.method == "POST":
		form = BigsForm(request.POST,request.FILES)
		if form.is_valid():
			newBigs = form.save(commit=False)
			newBigs.user = User.objects.get(id=request.session['user_id'])
			try:
				newBigs.save()
			except :
				return HttpResponse('Error')
		return HttpResponseRedirect(reverse('bigs-index'))
	else:
		form = BigsForm()
	return TemplateResponse(request, 'bigs/add.html',{'form':form})

def edit():
	pass

def show():
	pass

def references(request):
	p = request.GET.get('p')
	k = request.GET.get('keyword')
	if p == None:
		p = 1
	if k == None:
		k = ''

	if k != '':
		refs = Refs.objects.filter(Q(name__contains=k)|Q(author__contains=k)|Q(publisher__contains=k))
	else:
		refs = Refs.objects.all()
	paginator = extpaginator(refs, 10)
	pagestr = paginator.pagestr(p,{'k':k})
	try:
		prefs = paginator.page(p)
	except PageNotAnInteger:
		prefs = paginator.page(1)
	except EmptyPage:
		pusers = paginator.page(paginator.num_pages)
	return TemplateResponse(request, 'bigs/references.html',{'refs':prefs, 'pagestr':pagestr})

def addRef(request):
	if request.method == "POST":
		form = RefsForm(request.POST,request.FILES)
		if form.is_valid():
			try:
				form.save()
				return HttpResponse('Add Refs Successfully!')
			except :
				return HttpResponse('Error')
	else:
		form = RefsForm()
	return TemplateResponse(request, 'bigs/addRef.html',{'form':form})

def editRef(request,id):
	if request.method == "POST":
		a = Refs.objects.get(id=request.POST['id'])
		form = RefsForm(request.POST,instance=a)
		if form.is_valid():
			try:
				form.save()
			except :
				return HttpResponse('Error')
		return HttpResponseRedirect(reverse('bigs-references'))
	else:
		refs = Refs.objects.get(id=id)
		form = RefsForm(instance=refs)
		return TemplateResponse(request, 'bigs/editRef.html',{'form':form,'id':id})

def delRef(request,id):
	try:
		Refs.objects.filter(id=id).delete()
	except Exception as e:
		raise 'Can not delete the Ref'
	return HttpResponseRedirect(reverse('bigs-references'))

def showRef(request,id):
	ref = Refs.objects.get(id=id)
	return TemplateResponse(request, 'bigs/showRef.html', {'ref':ref})

bigs/templates/bigs/add.html
{% extends 'base.html' %}

{% block title %}新增事件{% endblock %}

{% block content %}
<link href="/static/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.css" rel="stylesheet" type="text/css"></link>

<div class="page-content-wrapper">
	<!-- BEGIN PAGE -->
	<div class="page-content">
		<div class="row">
			<div class="col-md-12">
				<!-- BEGIN PAGE TITLE & BREADCRUMB-->
				<h3 class="page-title">
					新增事件
				</h3>
				<ul class="breadcrumb">
					<li>
						<i class="icon-home"></i>
						<a href="">首页</a>
						<i class="icon-angle-right"></i>
					</li>
					<li>
						<a href="">大事件管理</a>
						<i class="icon-angle-right"></i>
					</li>
					<li>新增事件</li>

				</ul>
				<!-- END PAGE TITLE & BREADCRUMB-->
			</div>
		</div>

		<div class="row"><div class="col-md-9"><div class="form">
			<form method='post' class="horizontal-form" enctype="multipart/form-data">
				{% csrf_token %}
				{% for field in form %}
					<div class="">
						<div class="form-group"><div class="row">
							<div class="control-label col-md-2" style="text-align:right">{{ field.label}}</div>
							<div class="controls col-md-10">
								{{field}}
								<span class="help-block">{{field.errors}}</span>
							</div>

						</div></div>
					</div>
				{% endfor %}

				<div class="form-actions center">
					<button type="submit" class="btn blue"><i class="icon-ok"></i> 添 加</button>
					<button type="button" class="btn" id="cancel-btn">取 消</button>
				</div>
			</form>
		</div></div></div>

	</div>

</div>

{% endblock %}

{% block script %}
<script src="/static/plugins/bootstrap-wysihtml5/wysihtml5-0.3.0.js"></script>
<script src="/static/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>
<script>
	jQuery("#cancel-btn").click(function(){
		history.back();
	});

	$("#id_content,#id_memo").wysihtml5({"image":false});
</script>

{% endblock %}

bigs/templates/bigs/addRef.html
{% extends 'base.html' %}

{% block title %}新增文献{% endblock %}

{% block content %}
<link href="/static/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.css" rel="stylesheet" type="text/css"></link>

<div class="page-content-wrapper">
	<!-- BEGIN PAGE -->
	<div class="page-content">
		<div class="row">
			<div class="col-md-12">
				<!-- BEGIN PAGE TITLE & BREADCRUMB-->
				<h3 class="page-title">
					新增文献
				</h3>
				<ul class="breadcrumb">
					<li>
						<i class="icon-home"></i>
						<a href="">首页</a>
						<i class="icon-angle-right"></i>
					</li>
					<li>
						<a href="">大事件管理</a>
						<i class="icon-angle-right"></i>
					</li>
					<li>新增文献</li>

				</ul>
				<!-- END PAGE TITLE & BREADCRUMB-->
			</div>
		</div>

		<div class="row"><div class="col-md-9"><div class="form">
			<form method='post' class="horizontal-form" enctype="multipart/form-data">
				{% csrf_token %}
				{% for field in form %}
					<div class="">
						<div class="form-group"><div class="row">
							<div class="control-label col-md-2" style="text-align:right">{{ field.label}}</div>
							<div class="controls col-md-10">
								{{field}}
								<span class="help-block">{{field.errors}}</span>
							</div>

						</div></div>
					</div>
				{% endfor %}

				<div class="form-actions center">
					<button type="submit" class="btn blue"><i class="icon-ok"></i> 添 加</button>
					<button type="button" class="btn" id="cancel-btn">取 消</button>
				</div>
			</form>
		</div></div></div>

	</div>

</div>

{% endblock %}

{% block script %}
<script src="/static/plugins/bootstrap-wysihtml5/wysihtml5-0.3.0.js"></script>
<script src="/static/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>
<script>
	jQuery("#cancel-btn").click(function(){
		history.back();
	});

	$("#id_intro").wysihtml5({"image":false});
</script>

{% endblock %}

bigs/templates/bigs/editRef.html
{% extends 'base.html' %}

{% block title %}编辑文献{% endblock %}

{% block content %}
<link href="/static/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.css" rel="stylesheet" type="text/css"></link>

<div class="page-content-wrapper">
	<!-- BEGIN PAGE -->
	<div class="page-content">
		<div class="row">
			<div class="col-md-12">
				<!-- BEGIN PAGE TITLE & BREADCRUMB-->
				<h3 class="page-title">
					编辑文献
				</h3>
				<ul class="breadcrumb">
					<li>
						<i class="icon-home"></i>
						<a href="">首页</a>
						<i class="icon-angle-right"></i>
					</li>
					<li>
						<a href="">大事件管理</a>
						<i class="icon-angle-right"></i>
					</li>
					<li>编辑文献</li>

				</ul>
				<!-- END PAGE TITLE & BREADCRUMB-->
			</div>
		</div>

		<div class="row"><div class="col-md-9"><div class="form">
			<form method='post' class="horizontal-form" enctype="multipart/form-data">
				{% csrf_token %}
				{% for field in form %}
					<div class="">
						<div class="form-group"><div class="row">
							<div class="control-label col-md-2" style="text-align:right">{{ field.label}}</div>
							<div class="controls col-md-10">
								{{field}}
								<span class="help-block">{{field.errors}}</span>
							</div>

						</div></div>
					</div>
				{% endfor %}

				<div class="form-actions center">
					<input type="hidden" name="id" value="{{ id }}" />
					<button type="submit" class="btn blue"><i class="icon-ok"></i> 添 加</button>
					<button type="button" class="btn" id="cancel-btn">取 消</button>
				</div>
			</form>
		</div></div></div>

	</div>

</div>

{% endblock %}

{% block script %}
<script src="/static/plugins/bootstrap-wysihtml5/wysihtml5-0.3.0.js"></script>
<script src="/static/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>
<script>
	jQuery("#cancel-btn").click(function(){
		history.back();
	});

	$("#id_intro").wysihtml5({"image":false});
</script>

{% endblock %}

bigs/templates/bigs/index.html
{% extends 'base.html' %}

{% block title %}大事件表{% endblock %}

{% block content %}
<div class="page-content-wrapper">
	<!-- BEGIN PAGE -->
	<div class="page-content">
		<div class="row">
			<div class="col-md-12">
				<!-- BEGIN PAGE TITLE & BREADCRUMB-->
				<h3 class="page-title">
					大事件表
				</h3>
				<ul class="breadcrumb">
					<li>
						<i class="icon-home"></i>
						<a href="">首页</a>
						<i class="icon-angle-right"></i>
					</li>
					<li>
						<a href="">大事件管理</a>
						<i class="icon-angle-right"></i>
					</li>
					<li>大事件表</li>

				</ul>
				<!-- END PAGE TITLE & BREADCRUMB-->
			</div>
		</div>

		<div class="row">
			<div class="col-md-12">
				<!-- BEGIN EXAMPLE TABLE PORTLET-->
				<div class="portlet-body">
					<div class="table-toolbar"><div class="row">
						<div class="btn-group col-md-8">
							<a href="{% url 'bigs-add' %}" class="btn green">
								新增事件 <i class="fa fa-plus"></i>
							</a>
						</div>
						<form action="{% url 'bigs-index' %}" method="GET">
						<div class="col-md-4">
							<div class="input-group">
								<input type="text" class="form-control" name="keyword" >
								<span class="input-group-btn">
									<button class="btn blue" type="submit"><i class="fa fa-search"></i></button>
								</span>
							</div>
						</div></form>

					</div></div>

					<table class="table table-striped table-bordered table-hover">
						<thead>
							<tr>
								<th class="center">序号</th>
								<th class="">朝代</th>
								<th class="hidden-480 center">年代</th>
								<th class="hidden-480 center">月日</th>
								<th class="hidden-480 center">事件</th>
								<th>操作</th>
							</tr>
						</thead>

						<tbody>
							{% load admin_tags %}
							{% for item in bigs %}
								<tr class="odd gradeX">
									<td class="center">{{ item.id }}</td>
									<td class="">
										{{ item.era }}
									</td>
									<td class="hidden-480 center">{{ item.year }}</td>
									<td class="center hidden-480">{{ item.date }}</td>
									<td class="center hidden-480">{{ item.topic }}</td>

									<td >
										<a href="{% url 'admin-edit-user' item.id %}">编辑</a>										
									</td>
								</tr>
							{% endfor %}
						</tbody>

					</table>
					<div>
						{{ pagestr|safe }}
					</div>
				</div>
				<!-- END EXAMPLE TABLE PORTLET-->

			</div>

		</div>

	</div>

</div>

{% endblock %}

bigs/templates/bigs/references.html
{% extends 'base.html' %}

{% block title %}参考文献{% endblock %}

{% block content %}
<div class="page-content-wrapper">
	<!-- BEGIN PAGE -->
	<div class="page-content">
		<div class="row">
			<div class="col-md-12">
				<!-- BEGIN PAGE TITLE & BREADCRUMB-->
				<h3 class="page-title">
					参考文献
				</h3>
				<ul class="breadcrumb">
					<li>
						<i class="icon-home"></i>
						<a href="">首页</a>
						<i class="icon-angle-right"></i>
					</li>
					<li>
						<a href="">大事件管理</a>
						<i class="icon-angle-right"></i>
					</li>
					<li>参考文献</li>

				</ul>
				<!-- END PAGE TITLE & BREADCRUMB-->
			</div>
		</div>

		<div class="row">
			<div class="col-md-12">
				<!-- BEGIN EXAMPLE TABLE PORTLET-->
				<div class="portlet-body">
					<div class="table-toolbar"><div class="row">
						<div class="btn-group col-md-8">
							<a href="{% url 'bigs-addRef' %}" class="btn green">
								新增文献 <i class="fa fa-plus"></i>
							</a>
						</div>
						<form action="{% url 'bigs-references' %}" method="GET">
						<div class="col-md-4">
							<div class="input-group">
								<input type="text" class="form-control" name="keyword" >
								<span class="input-group-btn">
									<button class="btn blue" type="submit"><i class="fa fa-search"></i></button>
								</span>
							</div>
						</div></form>

					</div></div>

					<table class="table table-striped table-hover">
						<thead>
							<tr>
								<th class="center">#</th>
								<th class="right">文献名称</th>
								<th class="hidden-480 center">作者</th>
								<th class="hidden-480 center">出版社</th>
								<th class="hidden-480 center">出版时间</th>
								<th>操作</th>
							</tr>
						</thead>

						<tbody>
							<!-- {% load admin_tags %} -->
							{% for item in refs %}
								<tr class="odd gradeX">
									<td class="center">{{ item.id }}</td>
									<td class="text-right">
										<a href="{% url 'bigs-show-ref' item.id %}">{{ item.name }}</a>
									</td>
									<td class="hidden-480 center">{{ item.author }}</td>
									<td class="center hidden-480">{{ item.publisher }}</td>
									<td class="center hidden-480">{{ item.pubtime|date:"Y-m-d" }}</td>

									<td >
										<a href="{% url 'bigs-edit-ref' item.id %}">编辑</a> |
										<a href="{% url 'bigs-del-ref' item.id %}">删除</a>
									</td>
								</tr>
							{% endfor %}
						</tbody>

					</table>
					<div>
						{{ pagestr|safe }}
					</div>
				</div>
				<!-- END EXAMPLE TABLE PORTLET-->

			</div>

		</div>

	</div>

</div>

{% endblock %}

bigs/templates/bigs/showRef.html
{% extends 'base.html' %}

{% block title %}{{ ref.name }}{% endblock %}

{% block content %}
<div class="page-content-wrapper">
	<!-- BEGIN PAGE -->
	<div class="page-content">
		<div class="row">
			<div class="col-md-12">
				<!-- BEGIN PAGE TITLE & BREADCRUMB-->
				<h3 class="page-title">
					参考文献：{{ ref.name }}
				</h3>
			</div>
		</div>

		<div class="row">
			<div class="col-md-12">
				<!-- BEGIN EXAMPLE TABLE PORTLET-->
				<div class="portlet-body">
					<div class="row">
						<div class="col-md-5">
							<img src="{{ ref.cover.url }}" width="100%" />
						</div>
						<div class="col-md-7">
							<h3>{{ ref.name }}</h3>
							<p>作者： {{ref.author}}</p>
							<p>出版社：{{ref.publisher}}</p>
							<p>出版时间：{{ref.pubtime}}</p>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<p> {{ref.intro}}</p>
						</div>
					</div>


				</div>
				<!-- END EXAMPLE TABLE PORTLET-->

			</div>

		</div>

	</div>

</div>

{% endblock %}